### PR TITLE
Add PHP 8.4 support to Smarty

### PR DESCRIPTION
**Pull request by Visualq**
This pull request updates the code base to support the deprecations introduced in PHP 8.4. It should be backwards compatible.

1. Updated the function signatures that had implicit null assignment to typed parameters. 
2. Added PHP 8.4 to the 'run tests'-shell script.
3. Bumped the PHP version in the README.md

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
Wow... way to stay ahead of things. I support this effort in theory, but is the PHP 8.4 syntax 100% nailed down? Does it make sense to wait until we're 100% sure the syntax isn't gonna change.

I didn't even know PHP 8.4 alpha was out until I saw this issue :)

**Comment by Visualq** [comment]
> Wow... way to stay ahead of things. I support this effort in theory, but is the PHP 8.4 syntax 100% nailed down? Does it make sense to wait until we're 100% sure the syntax isn't gonna change.
> 
> I didn't even know PHP 8.4 alpha was out until I saw this issue :)

I ran the test suite against the PHP 8.4 alpha version (no errors/or deprecation warnings). There has been a feature stop and it appears that a lot of 'proposed' deprecations for PHP 8.4 are still being discussed (https://wiki.php.net/rfc/deprecations_php_8_4).  Functions that would require attention if all the deprecations are implemented/pass are:

- `md5()`
- `sha1()`
- `strtok()`
- passing `E_USER_ERROR` to `trigger_error()`
- `E_STRICT` Constant

The `md5()` and `sha1()` could be replaced with hash() however that would bump Smarty's minimum's PHP version to 8.0 or they could be polyfilled but this might be a performance debate. Maybe a simple `function_exists` could solve this without to much performance degredation

The `strtok()` is used once within Smarty and can be replaced.

The two deprecations regarding the error constants can easily be solved

This might not be a full PHP 8.4 support update for when it's released. The adjustments are safe down to PHP 7.1.

**Comment by eileenmcnaughton** [comment]
I took a look at this & support it being merged. I guess the only contentious part of merging it from my point of view is whether you want to declare php8.4 support - the other changes all seem to be fine as 'preparation' if you are not prepared to go all in

**Comment by marclaporte** [comment]
> is the PHP 8.4 syntax 100% nailed down

The next planned release is RC1 so syntax changes are unlikely at this point.
https://wiki.php.net/todo/php84

**Comment by carloscz** [comment]
Hi, PHP 8.4 should be released next week, we run compatibility tests and Smarty emits a lot of deprecation warnings solved in this PR so good job 👍 :) when do You think this could be released?

**Comment by Hlavtox** [comment]
PHP 8.4 coming thursday, let's go! :-)

**Review by wisskid — APPROVED** [review]

**Comment by eileenmcnaughton** [comment]
yay

**Comment by jolelievre** [comment]
Thanks @wisskid 

I proposed a similar PR for the version 4 https://github.com/smarty-php/smarty/pull/1084 mostly inspired by this one
It's my first time contributing on Smarty so I'm not sure if my PR has the right format, if it targets the right branch for Smarty 4

Also, the CI doesn't seem to run for now, maybe because a committer needs to approve the run?

**Comment by wisskid** [comment]
I’ll review and run the checks ASAP.thanks!Op 21 nov 2024 om 12:21 heeft Jonathan Lelievre ***@***.***> het volgende geschreven:﻿
Thanks @Visualq and @wisskid
I proposed a similar PR for the version 4 #1084 mostly inspired by this one
It's my first time contributing on Smarty so I'm not sure if my PR has the right format, if it targets the right branch for Smarty 4
Also, the CI doesn't seem to run for now, maybe because a committer needs to approve the run?

**Comment by eileenmcnaughton** [comment]
Thank you for your work on this!!

**Comment by scottchiefbaker** [comment]
PHP 8.5 is scheduled to land in November 2025. There will be release candidates well before that date that we can use to test and run the Smarty unit tests. It doesn't sound like there are any MAJOR feature changes so this should be a pretty smooth transition.

I've been using the [Sluz unit tests](https://github.com/scottchiefbaker/sluz) to validate new versions of PHP for years. It works great.

**Comment by wisskid** [comment]
I've prepared a release for PHP 8.5. When there is a docker image available, I'll run the unit tests. Judging from the changelog, this shouldn't require any changes at all.

**Pull request merged**
