### PR TITLE
Update smarty_internal_runtime_codeframe.php

### PR DESCRIPTION
**Pull request by avatec**
Update for php 8.1 strftime is deprecated

### CODE REVIEW

**Comment by artcs** [comment]
You cannot simply replace `strftime` with `date`. You have to update the formatstring accordingly (e.g. `'Y-m-d H:i:s'` instead of `%Y-%m-%d %H:%M:%S`).

**Comment by avatec** [comment]
> You cannot simply replace `strftime` with `date`. You have to update the formatstring accordingly (e.g. `'Y-m-d H:i:s'` instead of `%Y-%m-%d %H:%M:%S`).

You are right - so only need to remove those % and it will be done.

**Comment by artcs** [comment]
> so only need to remove those % and it will be done.

Not exactly. E.g. `%M` has to be replaces by `i`. Read the manual.

**Comment by wisskid** [comment]
@avatec we will work on a more comprehensive replacement for strftime soon, covering all occurences.

**Pull request closed without merging**
