### PR TITLE
Use Composer autoloader instead of Smarty_Autoloader

### PR DESCRIPTION
**Pull request by rudiedirkx**
All you have to do is change `composer.json`, which won't make Composer autoload `bootstrap.php` anymore, but make a classmap instead.

### CODE REVIEW

**Comment by AnrDaemon** [comment]
Do you think you're first one to suggest it? … :/

**Comment by AnrDaemon** [comment]
https://github.com/smarty-php/smarty/pull/416

**Comment by rudiedirkx** [comment]
I did. Why is your PR closed without comments?

In my local project I added a command to empty `bootstrap.php`, and added the classmap in my own repo:

    "autoload": {
        "classmap": [
            "vendor/smarty/smarty/libs"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "cat > vendor/smarty/smarty/libs/bootstrap.php"
        ]
    }

It's a little weird, but it works: no more Smarty autoloader.

**Comment by AnrDaemon** [comment]
post-autoload-dump is unnecessary.

**Comment by AnrDaemon** [comment]
P.S.
https://github.com/smarty-php/smarty/compare/master...AnrDaemon:use-classmaps?expand=1

**Comment by rudiedirkx** [comment]
Without it, Smarty will still install its own Autoloader, even though it's not used anymore.

**Comment by AnrDaemon** [comment]
Where? I remember I checked the code, but my conclusion was that it would no longer execute.

**Comment by AnrDaemon** [comment]
> Since bootstrap.php is still auto-included by Composer,

No, it's not.

**Comment by rudiedirkx** [comment]
Not with your PR, but with my local change. A composer patch can't change `composer.json`, so I can't un-auto-include `bootstrap.php`. How did you? Do you require your smarty fork instead of `smarty/smarty`?

**Comment by AnrDaemon** [comment]
I maintain private packagist and configure it for my projects.

**Comment by rudiedirkx** [comment]
You can change a contrib package's `composer.json` on private packagist?? I've no idea how private packagist works.

Anyways. Your and this PR is the right way to go. Why was your PR closed? And why no maintainer feedback?

**Comment by uwetews** [comment]
composer.json has been updated with #515

**Comment by rudiedirkx** [comment]
Excellent! I'm confused as to why it took at least 3 PRs, but whatevs. Great news. In `3.1.34`?

**Comment by AnrDaemon** [comment]
Would be, once it is out.
Thanks Uwe.

**Pull request closed without merging**
