### PR TITLE
This appears to fix #453, #498, #499 and possibly more issues. 

### LINKED ISSUE #453: isset() check fails within section $VAR[loop].key syntax if "key" or "loop" does not exist
Hello there!

I recently updated the Smarty library in a project from v3.1.30 to v3.1.32 and noticed, that this version seems to have a problem with the `isset()` check if a var is not set and I'm using the syntax you usually use to address something in a section with `$VAR[counter].subvalue`. As soon I roll back to v3.1.30 the same template code works again so I think it must have to do something with a change made in 3.1.31 or 3.1.32. I'm using both with PHP7.2 and error_reporting is set to strict including all notices for uninitialized vars in my dev environment.

Has the syntax just changed or does `[]` fail now due to a bug? (It worked on 3.1.30).

**I made an example for you here:**

```
- PAGE START
{section name=topics loop=$TOPICS}
  {if isset($TOPICS[topics].thisoneexists)}
     this one exists
  {/if}

  {if isset($TOPICS[topics].thisdoesnotexist)}
     this one does not exist
  {/if}

  {if isset($TOPICS[bla].blubb)}
     this doesn't even nearly exist ;)
  {/if}
{/section}
- PAGE END
```

With Smarty v3.1.30 I see:
```
- PAGE START
this one exists
- PAGE END

```

so this is the expected behaviour: The vars that are not existing in the section array fail the isset check, but the template gets compiled further to the end.

However on Smarty v3.1.32 I see:
```
- PAGE START
this one exists
```

In other words: As soon I have an isset with a non-existing array key the template stops to compile further and I end up just seeing a blank page. No message in the error log, no message when I turn on Smarty Debugging ... very mysterious.

~~The funny thing is when I write it like this `{if isset($TOPICS.topics.thisdoesnotexist)}` it seems to work.~~
> **EDIT:** Correction, this is also no option to solve the problem! I just noticed the method with dots doesn't work in sections. This will always return a false isset() check even if a value is set. So it seems I definitely need the `$TOPICS[topics].thisdoesnotexist` Syntax here.

Am I doing something wrong here or is that a bug? It makes me wonder that the syntax with `[]` does NOT fail if the value is really set and only fails when its not set, so if you got rid of the `[]` variant and there is a different syntax for sections, shouldn't this fail with a syntax error in both cases then? Or shouldn't it behave like in 3.1.30 where using that worked correctly and nonexistant values didn't cause the template compiling to stop/fail?

Thanks in advance!

### PR DESCRIPTION
**Pull request by wisskid**
Will need further testing and unit tests.

Using the @-operator will supress errors generated in code wrapped in the `isset()` call. That's not good. Better than what we have now, but not ideal.

### CODE REVIEW

**Comment by wisskid** [comment]
Another approach would be to improve the regex that tries to determine whether `$p` is a variable. This might do it:
`^\$[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*((->)[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*|\[[^\]]*\])*$`

**Comment by wisskid** [comment]
Slight improvement to balance out brackets with nested brackets: `^\$[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*((->)[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*|\[.*]*\])*$`

**Comment by uwetews** [comment]
Please note that the issues at handling isset() and empty() calls can get much more complex.
If the variable tested is an object its properties can be variable.
Array indexes may contain variables.
You will get runtime errors when some of this subvariables are undefined.
I was working on a solution before I got ill last year.
I should be able to work on this problem in about 2-3 weeks

**Comment by wisskid** [comment]
@uwetews great to hear you are coming back! I was thinking a truly proper solution would require lexing/parsing the parameter to ensure it's a valid php variable instead of using a regex. But my solution posted above seems pretty effective too.
I'd love to hear your thoughts. Get well soon!

**Comment by wisskid** [comment]
@uwetews a similar fix in `libs/plugins/modifiercompiler.default.php` would fix https://github.com/smarty-php/smarty/issues/336

**Comment by glensc** [comment]
please note that you can't really get by pattern match accurate result whether 
 `empty()` argument is non-variable.

see discussion and example here:
- https://github.com/PHPCompatibility/PHPCompatibility/issues/410

**Pull request merged**
