### PR TITLE
PHP 5.3 compatibility fixes

### PR DESCRIPTION
**Pull request by AnrDaemon**

### CODE REVIEW

**Comment by AnrDaemon** [comment]
@wisskid tck-tck-tck…

**Comment by wisskid** [comment]
Ouch

**Comment by AnrDaemon** [comment]
In this light, I'd like to raise https://github.com/smarty-php/smarty/issues/353#issuecomment-615367537 once more.

Stuff moving forward and supporting highly outdated engine versions becoming increasingly problematic.

I've had to spend half an hour just to be able to successfully run tests using 5.3. AFTER the moment I fixed linting errors. I'm not sure it can be run on 5.2 anymore. (Though, Composer only supports 5.3.2+, so the point is probably moot.)

**Comment by wisskid** [comment]
I was afraid you’d bring that up now. Now, I don’t see why we’d have to support 5.3 or older anymore. It’s been EOL almost six years. But dropping php5.6 could cause some actual pain, right?

And, jus being curious, how did you notice this? Are you still running 5.3?

**Comment by AnrDaemon** [comment]
EOL or not, Smarty declares compatibility (right now, with 5.2+, but in fact I doubt it can run on anything older than 5.3) with certain PHP version. Changing minimum engine version and retain the same library version is a bad service, IMO.

This is why I suggest changing version number to move things forward. We can keep 3.1/5.3 branch in case something crop up that would require urgent attention, but other than that, I see only benefits.

Even language defaults were changed long before 7.x. Just look at the recent #590. Not that the code could have been shorter, the final version took much care about preserving set encodings where possible, but default settings for both mb_regex_encoding and mb_internal_encoding were changed not once since 5.3.

No, I'm not using 5.3 daily, but I keep it fully operational for regression tests.

**Comment by wisskid** [comment]
I totally agree. When we start dropping compatibility with certain php versions, we should up the version number. And we should get unit tests running in travis for each php version that we support.
But if we can easily support php5.6, then I don't see any harm in doing so, right?

**Comment by AnrDaemon** [comment]
Let's move it to a separate issue, shall we?

**Pull request merged**
