### PR TITLE
PHP 7.2:

### PR DESCRIPTION
**Pull request by mambax7**
The each() function is deprecated.
Function create_function() is deprecated

Would these changes work?

### CODE REVIEW

**Comment by uwetews** [comment]
It should work, however because of the use of a closure the patch is not compatible with PHP 5.2.

I will release during the comming week 2.6.31 which will implement the callback as method. At the same time I will have also the PHPUnit tests ready including PHP 7.2.
So please wait a few days.

**Comment by nao-pon** [comment]
@uwetews ping. how about it?

**Comment by uwetews** [comment]
I have just released 2.6.31 has the deprecatedfunctions replaced

**Comment by nao-pon** [comment]
Thanks! 👍

**Comment by vuongmn** [comment]
> 
> I have just released 2.6.31 has the deprecatedfunctions replaced

@uwetews ,
Please help me check my Q&A in issue #493 ( Release note of v2.6.31 is sooner than PHP7.2.0)

**Pull request closed without merging**
