### PR TITLE
FIX: throw $e will swallow exception stacktrace

### PR DESCRIPTION
**Pull request by quamis**
use throw new Exception with 3'rd parameter filled in, to throw a new
exception

### CODE REVIEW

**Comment by wisskid** [comment]
@quamis what problem are you trying to fix?

**Comment by quamis** [comment]
Exceptions thown by non-smarty-code in tpl's had their stacktrace truncated, because smarty was catching exceptions and re-throwing them without attaching the old exception. This method of re-throwing didn't allow propagating the original stacktrace from the original exception, and it made debugging really hard, because all exceptions seemed to occur in the smarty core.

**Comment by quamis** [comment]
Sorry, I've re-reviewd the changes and I wasn't remembering the whole picture.

Smarty was doing a lot of `throw $e`, but this will throw back the original exception, without recording where and why it was changed and re-thrown(and keeping only the original stacktrace, without the stacktrace where smarty was actually involved). 

Doing `throw new Exception("...reason..", null, $e)` will keep the original stacktrace, and allow adding messages like "fetch failed", "compile failed", etc. This should allow easier debugging, as the developer will know where this exception was cached/thrown. 

The downside seems to be that all exception will get re-mapped to the base Exception class, so this will not allow doing

```
try {
   $smarty->fetch("abc.tpl");
} catch( Exception1 $e) {
   // handle exception
} catch( Exception2 $e) {
   // handle exception
}

```

**Comment by wisskid** [comment]
@quamis I think you are right, people will be depending on specific Exception classes, so we shouldn't change that.

**Pull request closed without merging**
